### ISSUE TITLE
need to stick with version 8.3

### ISSUE THREAD

**Issue by wumpz** [plutext/docx4j-ImportXHTML#104]
Unfortunately, I have to stick with the 8.3 version. However due to issue https://www.docx4java.org/forums/docx-java-f6/new-namespace-mapping-issue-t3112.html I need to upgrade to docx4j 8.3.10. This version is not compatible with docx4j-ImportXHTML 8.3.8, since e.g. FormatingOptions class was moved or removed. 

When can you release an actualized version 8.3.10 of docx4j-ImportXHTML?

**Comment by plutext** [comment]
Will get onto this next week

**Comment by plutext** [comment]
As per https://www.docx4java.org/forums/docx-java-f6/docx4j-importxhtml-8-3-10-released-t3118.html there is now

```
<dependency>
    <groupId>org.docx4j</groupId>
    <artifactId>docx4j-ImportXHTML</artifactId>
    <version>8.3.10</version>
</dependency>
```

**Comment by wumpz** [comment]
Thx
