### ISSUE TITLE
List elements are imported incorrectly

### ISSUE THREAD

**Issue by andreysubbotin** [plutext/docx4j-ImportXHTML#39]
I'd like to import HTML like:
`<html><head></head><body>More content to test:<div><ul><li>Item 1</li><li>Item 2</li><li>Item 3</li><li>Item 4</li></ul></div></body></html>`

Actual DOCX file without a list. See attachment
 
[TestReport (26).docx](https://github.com/plutext/docx4j-ImportXHTML/files/1383024/TestReport.26.docx)

**Comment by plutext** [comment]
Looks OK to me using https://www.docx4java.org/docx4j/docx4j-ImportXHTML-nightly-20171011.jar

Please describe your issue more fully?

**Comment by andreysubbotin** [comment]
Hi, 
I found a problem in my code for DOCX generation.
Thanks for your help.
